# Generated by Django 4.0.7 on 2022-09-21 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import thorn.utils.django.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webhooks', '0003_auto_20171024_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='event',
            field=thorn.utils.django.fields.ChoicesCharField(db_index=True, help_text='Name of event to connect with', max_length=190, verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
    ]
